### ISSUE TITLE
'mask_camera' question

### ISSUE THREAD

**Issue by fangchengji** [hustvl/osp#1]
How to get 'mask_camera' when you run model inference in vehicle?

**Comment by shawnsya** [comment]
The mask_camera is used for the evaluation of Occ3D-nuS and is not needed during inference.

**Comment by Yzichen** [comment]
https://github.com/hustvl/osp/blob/573dc48a06a4d11e00a354c8cd833636ee91aaf9/projects/mmdet3d_plugin/bevformer/dense_heads/bevformer_occ_head.py#L256-L261

So this isn't the inference process?

**Comment by Grimxiaohao** [comment]
> https://github.com/hustvl/osp/blob/573dc48a06a4d11e00a354c8cd833636ee91aaf9/projects/mmdet3d_plugin/bevformer/dense_heads/bevformer_occ_head.py#L256-L261
> 
> So this isn't the inference process?

I also found this problem, it is impossible to know 'mask_camera' when infering logically.

**Comment by shawnsya** [comment]
This infer process is the evaluation on Occ3D-nuS, so we have the mask_camera.

**Comment by MSunDYY** [comment]
The same question as above.
