### ISSUE TITLE
Config and code modification for BEVFormer w/OSP

### ISSUE THREAD

**Issue by DengpanFu** [hustvl/osp#2]
Hi, Thanks for your good job!
I am trying to reproduce the result(mIoU=41.21) of BEVFormer w/OSP, but can not find the correct config. In your [README-Results](https://github.com/hustvl/osp/blob/main/README.md#results), `OSP` and `BEVFormer w/OSP` share the same config(projects/configs/osp.py), could you please provide the detailed config for `BEVFormer w/OSP`(e.g., the config to freeze trained BEVFormer)? Besides, I have some other questions:

1. why self-attn [osp.py](https://github.com/hustvl/osp/blob/main/projects/configs/osp/osp.py#L122) is not needed in OSP?
2. there are 3 encoder layers, but each layer forward twice [BEVFormerEncoder](https://github.com/hustvl/osp/blob/main/projects/mmdet3d_plugin/bevformer/modules/encoder.py#L286-L308), why? Any explanation is appreciated.
3. i find a hard-code `use_bev_volume=False`, is this should be `True` for using OSP as a plugin to argument volume-based methods? and how to modify the code?

Looking forward to your reply, Thanks!

**Comment by shawnsya** [comment]
Hi! 
The config for BEVFormer can refer to the baseline provided by the CVPR2023 Challenge.
1. The input query only interacts with the images and does not require self-attention.
2. This part can refer to the oversample and GPCA mentioned in the paper.
3. Thank you for pointing that out. This hard-code was added in a previous experiment and will be removed.

**Comment by fky-pku** [comment]
Have you reproduced this result? Did you use the "projects/configs/osp.py" file for it?

**Comment by fky-pku** [comment]
Have you reproduced this result? Did you use the "projects/configs/osp.py" file for it?
